config/routes.rb
Rails.application.routes.draw do

  resources :issues
  resources :projects
  devise_for :users
  root 'site#index'
  get '/projects/:id/issues/new(.:format)' => 'issues#new'
  post '/projects/:id/issues/new(.:format)' => 'issues#create'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :issue
  # ensure that a user_id is present
  validates :user_id, presence: true

  # ensure that title is present and at least 10 chars long

  # ensure the url is present, and respects the URL format for http/https
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :project
	has_many :issue
  	devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = current_user.issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = current_user.issue.new
    @project = Project.find(params[:id])
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = current_user.issue.new(issue_params)

    respond_to do |format|
      @project = Project.find(params[:project_id])
      @project.issue << @issue
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = current_user.issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :description, :privacy)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/issues/_form.html.erb
<div class="login">
  	<div class="container">
    	<div class="form">
			<%= simple_form_for(@issue) do |f| %>
			  <%= f.error_notification %>

			  <div class="form-inputs">
			    <%= f.input :title %>
			    <%= f.input :description %>
			    <%= f.input :privacy %>
			    <%= hidden_field_tag 'project_id', @project.id %>
			  </div>

			  <div class="form-actions">
			    <%= f.button  :submit,class: "btn-submit" %>
			  </div>
			<% end %>
		</div>
	</div>
</div>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Issues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Privacy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.title %></td>
        <td><%= issue.description %></td>
        <td><%= issue.privacy %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1 style="text-align:center">New Issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @issue.description %>
</p>

<p>
  <strong>Privacy:</strong>
  <%= @issue.privacy %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <link href="http://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,300' rel='stylesheet' type='text/css'>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <title>Issuetracker</title>
  <body>

    <div class="header">
      <div class="container">
        <%= link_to root_path do %>
          <img src="http://s3.amazonaws.com/codecademy-content/courses/rails-auth/img/fotofoto-logo.svg" width="80" height="80">
        <% end %>
        <div class="nav pull-right">
          <% if current_user %> 
            <ul> 
              <li><%= current_user.email %></li> 
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li> 
            </ul> 
          <% else %> 
            <ul> 
              <li><a href="/users/sign_in">Login</a></li> 
              <li><a href="/users/sign_up">Signup</a></li> 
            </ul> 
          <% end %>



          
        </div>
      </div>
    </div>


    <%= yield %>

  </body>
</html>

app/views/projects/_form.html.erb
<div class="login">
  	<div class="container">
    	<div class="form">
			<%= simple_form_for(@project) do |f| %>
			  <%= f.error_notification %>

			  <div class="form-inputs">
			    <%= f.input :title ,:placeholder => "Project Name"%>
			  </div>

			  <div class="form-actions">
			    <%= f.button :submit ,class: "btn-submit"%>
			  </div>
			<% end %>
		</div>
	</div>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="container">
  <div class="col-md-4">
    <p id="notice"><%= notice %></p>

    <h1>Listing Projects</h1>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= project.title %></td>
            <td><%= link_to 'Show', project %></td>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
            <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Project', new_project_path %>
  </div>
</div>

app/views/projects/new.html.erb
<h1 style="text-align:center">New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="container">
	<div class="col-md-4">
		<p id="notice"><%= notice %></p>

		<h3>
		  Project Title:
		  <%= @project.title %>
		</h3>
		<h3><a href="/projects/<%= @project.id %>/issues/new">Click </a>here to create a new issue</h3> <br>
		<%= link_to 'Edit', edit_project_path(@project) %> |
		<%= link_to 'Back', projects_path %>
	</div>
</div>

app/views/site/index.html.erb
<div class="container">
	<div class="col-md-4">
		<% if current_user %> 
			<h3><a href="/projects/">Go to Project Page</a></h3>
		<% end %>
	</div>
</div>